### ISSUE TITLE
Allow passing IP address to authuser

### ISSUE THREAD

**Issue by amato-gianluca** [qcoumes/wimsapi#6]
Hi,
I am using Wims-LTI and I have the problem that when a student inadvertently closes the window with a WIMS exam, he has no way to continue this exam since every further attempt of launching it trough the LMS actually starts a new session instead of reusing the old one.

I think the problem is that Wims-LTI does not pass the IP address of the user to WIMS. Actually, Wims-LTI cannot pass the IP address, since the authuser method in the WimsAPI class does not have this feature. Therefore, what I am proposing is:
1) add a new parameter to the authuser method, whose default is None
2) if the value of this parameter is different from None, copy it into the params dictionary with they key 'data1' (which is where WIMS expects the IP address)

If you agree with this proposal, I would be happy to prepare and submit a pull request.

**Comment by qcoumes** [comment]
@amato-gianluca Seems perfect to me, I'll wait for your PR !

**Comment by qcoumes** [comment]
@amato-gianluca Opened a new issue on wims-lti about this problem : PremierLangage/wims-lti#49
